FROM oven/bun:1.3 AS base
WORKDIR /app

COPY shared/db ./shared/db
COPY db-poller ./db-poller
COPY engine ./engine
COPY scripts ./scripts

WORKDIR /app/shared/db
RUN bun install

WORKDIR /app/db-poller
RUN bun install

WORKDIR /app/engine
RUN bun install

WORKDIR /app/scripts
RUN bun install

COPY start-background.sh /app/start-background.sh
RUN chmod +x /app/start-background.sh

CMD ["/app/start-background.sh"]
